#
# IF this files is missing, then no Ping Library items will be created
#

example-item1:
  on:
    check_suite:               # compares check_suite:
      status: "completed"      # compares   status: completed
      
  item:
    title: "Terraform Role Assignment Module Example"
    content:
      description: "This is the card short description"
      html: "This is the longer description.  It is optional and if not, set, the short-description will be shown"
    metadata:
      contentType: "terraform-module"
      alias: "tm-example-users"
      
  terraform-module:    
    base-path: "examples/users"                                 # base path of the example files
    include-files: ["main.tf", "subdir2/providers.tf"]          # list of files to include. DEFAULT: list eveything (main.tf if found (expanded), is first, and then alphabetical)
    

#code:
#collection:
#dvcomponent:
#flow:
#page:
#pingone:
#terraform:
#terraform-module:
#redirect:
#js-snippets:

