#
# IF this files is missing, then no Ping Library items will be created
#

items:
  example-users:
    on: "check-suite"    # or push or pull request or ???
    name: "Terraform Role Assignment Module Example"
    short-description: "This is the card short description"
    long-description: "This is the longer description.  It is optional and if not, set, the short-description will be shown"
    terraform-module:
      base-path: "examples/users"                                 # base path of the example files
      include-files: ["main.tf", "subdir2/providers.tf"]          # list of files to include. DEFAULT: list eveything (main.tf if found (expanded), is first, and then alphabetical)
    

#code:
#collection:
#dvcomponent:
#flow:
#page:
#pingone:
#terraform:
#terraform-module:
#redirect:
#js-snippets:

